# This is a basic workflow to help you get started with Actions

name: WORKFLOWWWWW :3 YIPEEEE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

   

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Libs
        run: |
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib run flixel-tools setup
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hscript-improved https://www.github.com/YoshiCrafter29/hscript-improved
          haxelib git scriptless-polymod https://github.com/SrtHero278/scriptless-polymod
          haxelib install hxCodec
      - name: Compile
        run: haxelib run lime build windows -debug -clean
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: WINDOWSSS
          path: export/release/windows/bin

